plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.oduva-marga'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	// web
	implementation('org.springframework.boot:spring-boot-starter-web')
	// oauth 2 server setup
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
	// data validation
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	// database
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'
	// getter setter
	compileOnly "org.projectlombok:lombok:1.18.48"
	annotationProcessor "org.projectlombok:lombok:1.18.48"
	// mapper
	implementation "org.mapstruct:mapstruct:1.6.3"
	annotationProcessor "org.mapstruct:mapstruct-processor:1.6.3"
    // docs
	implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:3.1.0"
	// keycloak
	implementation "org.keycloak:keycloak-admin-client:26.0.12"


	// testing
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation 'org.springframework.security:spring-security-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'

	testCompileOnly "org.projectlombok:lombok:1.18.48"
	testAnnotationProcessor "org.projectlombok:lombok:1.18.48"
}

tasks.named('test') {
	useJUnitPlatform()
}
