spring:
  application:
    name: oduva-marga
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://auth.om.local/realms/test}
          audiences: ${AUDIENCE:oduvamarga_api}
  jpa:
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
  threads:
    virtual:
      enabled: true

server:
  port: ${SERVER_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
