spring:
  application:
    name: oduva-marga
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:543/iduvamarga}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:user}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://auth.om.local/realms/test}
          audiences: ${AUDIENCE:oduvamarga_api}

server:
  port: ${SERVER_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
